Repository cucumber/cucumber-js, pull requests merged in 2021-07, with the labels that each got.

#1709 [WIP] remove lodash
  features/custom_stack_trace.feature
  features/step_definitions/message_steps.ts
  features/step_definitions/usage_json_steps.ts
  features/support/formatter_output_helpers.ts
  features/support/message_helpers.ts
  features/support/world.ts
  package.json
  src/cli/argv_parser.ts
  src/cli/configuration_builder.ts
  src/cli/helpers.ts
  src/cli/i18n.ts
  src/cli/profile_loader.ts
  src/formatter/get_color_fns.ts
  src/formatter/helpers/event_data_collector.ts
  src/formatter/helpers/gherkin_document_parser.ts
  src/formatter/helpers/keyword_type.ts
  src/formatter/helpers/pickle_parser.ts
  src/formatter/helpers/summary_helpers.ts
  src/formatter/helpers/test_case_attempt_parser.ts
  src/formatter/helpers/usage_helpers/index.ts
  src/formatter/json_formatter.ts
  src/formatter/rerun_formatter.ts
  src/formatter/rerun_formatter_spec.ts
  src/formatter/summary_formatter.ts
  src/formatter/usage_formatter.ts
  src/models/data_table.ts
  src/pickle_filter.ts
  src/runtime/assemble_test_cases.ts
  src/runtime/index.ts
  src/runtime/parallel/coordinator.ts
  src/runtime/step_runner.ts
  src/runtime/test_case_runner.ts
  src/stack_trace_filter.ts
  src/support_code_library_builder/build_helpers.ts
  src/support_code_library_builder/index.ts
  src/support_code_library_builder/validate_arguments.ts
  tsconfig.json
  yarn.lock
Labels: :bank: debt

#1566 expose promise timeout helper
  dependency-lint.yml
  docs/support_files/timeouts.md
  features/attachments.feature
  features/before_after_all_hook_interfaces.feature
  features/failing_steps.feature
  features/hook_interface.feature
  features/parallel.feature
  features/parameter_types.feature
  features/passing_steps.feature
  features/step_definition_timeouts.feature
  src/cli/configuration_builder.ts
  src/cli/index.ts
  src/formatter/progress_bar_formatter_spec.ts
  src/index.ts
  src/models/step_definition.ts
  src/runtime/index.ts
  src/runtime/parallel/worker.ts
  src/time.ts
  src/time_spec.ts
  src/user_code_runner.ts
  src/user_code_runner_spec.ts
  test/formatter_helpers.ts
Labels: :bank: debt, :zap: enhancement

#1722 Add a 'reindent' test helper
  package.json
  src/formatter/helpers/gherkin_document_parser_spec.ts
  src/formatter/helpers/issue_helpers_spec.ts
  src/formatter/progress_formatter_spec.ts
  src/formatter/step_definition_snippet_builder/javascript_snippet_syntax_spec.ts
  src/formatter/usage_formatter_spec.ts
  yarn.lock
Labels: :bank: debt, :wrench: build, :zap: enhancement
