Repository cucumber/cucumber-js, pull requests merged in 2021-09, with the labels that each got.

#1793 Increase precision of test case duration measurements.
  CHANGELOG.md
  features/support/helpers.ts
  src/formatter/usage_formatter.ts
  src/formatter/usage_formatter_spec.ts
  src/time.ts
Labels: :zap: enhancement

#1531 fix(formatter): Enable calling parseTestCaseAttempt on test cases that haven't completed
  src/formatter/helpers/test_case_attempt_parser.ts
  src/formatter/helpers/test_case_attempt_parser_spec.ts
Labels: :zap: enhancement

#1649 add ESM support (take 2)
  CHANGELOG.md
  README.md
  dependency-lint.yml
  docs/esm.md
  features/direct_imports.feature
  features/esm.feature
  features/profiles.feature
  features/support/hooks.ts
  package-lock.json
  package.json
  src/cli/argv_parser.ts
  src/cli/configuration_builder.ts
  src/cli/configuration_builder_spec.ts
  src/cli/index.ts
  src/cli/profile_loader.ts
  src/cli/profile_loader_spec.ts
  src/formatter/builder.ts
  src/formatter/helpers/issue_helpers_spec.ts
  src/formatter/progress_bar_formatter_spec.ts
  src/importer.js
  src/runtime/parallel/worker.ts
  src/wrapper.mjs
  test/formatter_helpers.ts
  tsconfig.json
Labels: :zap: enhancement

#1800 add rule to keywords for i18n command
  features/i18n.feature
  src/cli/i18n.ts
Labels: :book: documentation

#1801 debt: remove --predictable-ids option
  CHANGELOG.md
  compatibility/cck_spec.ts
  features/step_definitions/formatter_steps.ts
  features/support/formatter_output_helpers.ts
  features/support/world.ts
  src/cli/argv_parser.ts
  src/cli/configuration_builder.ts
  src/cli/configuration_builder_spec.ts
  src/cli/index.ts
  src/runtime/index.ts
  src/runtime/parallel/coordinator.ts
  src/runtime/parallel/worker.ts
  test/runtime_helpers.ts
Labels: :bank: debt
