Repository cucumber/cucumber-js, pull requests merged in 2021-06, with the labels that each got.

#1568 Empty rerun file exits running no scenarios (#1302)
  CHANGELOG.md
  features/rerun_formatter.feature
  src/cli/configuration_builder.ts
  src/cli/configuration_builder_spec.ts
  src/cli/index.ts
Labels: :bug: bug, :dollar: bounty $300

#1697 debt: add things to main entry point that people need
  src/index.ts
  src/support_code_library_builder/types.ts
  test-d/hooks.ts
Labels: :bank: debt

#1699 refactor documentation (part 1)
  README.md
  docs/cli.md
  docs/parallel.md
  docs/profiles.md
  docs/retry.md
  docs/support_files/world.md
Labels: :book: documentation

#1703 Fixed reports banner to point to https://cucumber.io/docs/cucumber/environment-variables/
  CHANGELOG.md
  features/publish.feature
  src/cli/publish_banner.ts
Labels: :book: documentation

#1705 Add more arrow function warnings
  docs/faq.md
  docs/support_files/api_reference.md
  docs/support_files/hooks.md
  docs/support_files/step_definitions.md
  docs/support_files/world.md
Labels: :book: documentation

#1704 update supported node versions
  .github/workflows/build.yml
  CHANGELOG.md
  package.json
Labels: :broken_heart: breaking change, :wrench: build

#1713 cli: remove deprecated retryTagFilter option
  CHANGELOG.md
  features/retry.feature
  src/cli/argv_parser.ts
  src/cli/configuration_builder.ts
Labels: :bank: debt, :broken_heart: breaking change
