Repository cucumber/cucumber-js, pull requests merged in 2022-01, with the labels that each got.

#1895 chore: switch from colors to chalk
  CHANGELOG.md
  features/support/warn_user_about_enabling_developer_mode.ts
  features/support/world.ts
  package-lock.json
  package.json
  src/cli/publish_banner.ts
  src/formatter/get_color_fns.ts
Labels: :robot: dependencies, :bank: debt

#1901 chore: update @cucumber libraries to latest
  CHANGELOG.md
  package-lock.json
  package.json
  src/support_code_library_builder/index.ts
Labels: :robot: dependencies

#1899 Update world.md
  docs/support_files/world.md
Labels: :book: documentation

#1905 build: tag as next when publishing release candidates
  .github/workflows/release-npm-latest.yaml
  .github/workflows/release-npm-next.yaml
Labels: :wrench: build
